# ##### MAIN SETTINGS ########
# settings that effect which results will be created

analysis_design: false
# list of experiment names in the max quant file
# if false it will try to infer the experiments automatically
# TODO naming convention
# otherwise might look something like:
# - Urea_Urea_Pellet_0
# - RIPA_SDS_0

pathways: []
# list of pathways which should be analyzed

go_terms: []
# list of go_terms which should be analyzed

has_replicates: true
# does the file have replicates
# can be "true" or "false"

levels: 3

level_names: ["0", "1", "2"]

# ###### PLOT CREATION SETTINGS #######

plot_detection_counts_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_number_of_detected_proteins_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_intensity_histograms_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_relative_std_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_rank_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_pathway_analysis_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_scatter_replicates_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_experiment_comparison_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_go_analysis_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_venn_results_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_pathway_timecourse_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_r_volcano_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_venn_groups_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

plot_pca_overview_settings:
  create_plot: false
  dfs_to_use: []
  levels: []

use_protein_id: false
# should the protein id be used, or TODO
# can be "true" or "false"

equal_variance: false
# should equal variance be assumed for the t-test?
# can be "true" or "false"
