# ##### MAIN SETTINGS ########
# settings that effect which results will be created

experiments: false
# list of experiment names in the max quant file
# if false it will try to infer the experiments automatically
# TODO naming convention
# otherwise might look something like:
# - Urea_Urea_Pellet_0
# - RIPA_SDS_0

pathways: false
# list of pathways which should be analyzed

go_terms: false
# list of go_terms which should be analyzed

has_replicates: true
# does the file have replicates
# can be "true" or "false"

# ###### PLOT CREATION SETTINGS #######

plot_detection_counts: true
plot_detection_counts_intensity: "raw"

plot_number_of_detected_proteins: true
plot_number_of_detected_proteins_intensity: "raw"

plot_intensity_histograms: true
plot_intensity_histograms_intensity: "raw"

plot_relative_std: true
plot_relative_std_intensity: "raw"

plot_rank: true
plot_rank_intensity: "raw"

plot_pathway_analysis: true
plot_pathway_analysis_intensity: "raw"

plot_pathway_proportions: true
plot_pathway_proportions_intensity: "raw"

plot_scatter_replicates: true
plot_scatter_replicates_intensity: "raw"

plot_experiment_comparison: true
plot_experiment_comparison_intensity: "raw"

plot_go_analysis: true
plot_go_analysis_intensity: "raw"

plot_venn_results: true
plot_venn_results_intensity: "raw"

plot_venn_groups: true
plot_venn_groups_intensity: "raw"

plot_pathway_timeline: true
plot_pathway_timeline_intensity: "raw"

plot_r_volcano: true
plot_r_volcano_intensity: "raw"

use_protein_id: false
# should the protein id be used, or TODO
# can be "true" or "false"

equal_variance: false
# should equal variance be assumed for the t-test?
# can be "true" or "false"

# ##### IMAGE SETTINGS ########